model: qwen2.5-coder:7b
open_ai_key: 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
